export type PublicationLink = { label: "Paper" | "Code" | "Project" | "Video" | "DOI"; href: string };
export type Publication = {
  title: string;
  authors: string;
  venue: string;
  year: string;
  note?: string;
  links: PublicationLink[];
  placeholder: boolean;
};

export const publications: Publication[] = [
  {
    title: "Formal Verification and Control With Conformal Prediction: Practical Safety Guarantees for Autonomous Systems",
    authors: "Lars Lindemann, Yiqi Zhao, Xinyi Yu, George J. Pappas, Jyotirmoy V. Deshmukh",
    venue: "IEEE Control Systems Magazine",
    year: "2025",
    note: "Volume 45, Issue 6, pages 72–122",
    links: [{ label: "Paper", href: "https://ieeexplore.ieee.org/document/11274485/" }],
    placeholder: false,
  },
  {
    title: "Distributionally Robust Predictive Runtime Verification under Spatio-Temporal Logic Specifications",
    authors: "Yiqi Zhao, Emily Zhu, Bardh Hoxha, Georgios Fainekos, Jyotirmoy V. Deshmukh, Lars Lindemann",
    venue: "ACM Transactions on Cyber-Physical Systems",
    year: "2025",
    note: "Volume 9, Issue 4, pages 1–26",
    links: [{ label: "Paper", href: "https://doi.org/10.1145/3748818" }],
    placeholder: false,
  },
  {
    title: "STL-GO: Spatio-Temporal Logic with Graph Operators for Distributed Systems with Multiple Network Topologies",
    authors: "Yiqi Zhao, Xinyi Yu, Bardh Hoxha, Georgios Fainekos, Jyotirmoy V. Deshmukh, Lars Lindemann",
    venue: "ACM Transactions on Embedded Computing Systems",
    year: "2025",
    note: "Volume 24, Issue 5s, pages 1–23",
    links: [{ label: "Paper", href: "https://doi.org/10.1145/3760258" }],
    placeholder: false,
  },
  {
    title: "Conformal Predictive Monitoring for Multi-Modal Scenarios",
    authors: "Francesca Cairoli, Luca Bortolussi, Jyotirmoy V. Deshmukh, Lars Lindemann, Nicola Paoletti",
    venue: "International Conference on Runtime Verification",
    year: "2025",
    note: "Pages 336–356",
    links: [{ label: "Paper", href: "https://doi.org/10.1007/978-3-032-05435-7_19" }],
    placeholder: false,
  },
  {
    title: "Neuro-Symbolic Acceleration of MILP Motion Planning with Temporal Logic and Chance Constraints",
    authors: "Junyang Cai, Weimin Huang, Jyotirmoy V. Deshmukh, Lars Lindemann, Bistra Dilkina",
    venue: "arXiv preprint",
    year: "2025",
    links: [{ label: "Paper", href: "https://arxiv.org/abs/2508.07515" }],
    placeholder: false,
  },
  {
    title: "ConformalNL2LTL: Translating Natural Language Instructions into Temporal Logic Formulas with Conformal Correctness Guarantees",
    authors: "Jun Wang, David Smith Sundarsingh, Jyotirmoy V. Deshmukh, Yiannis Kantaros",
    venue: "arXiv preprint",
    year: "2025",
    links: [{ label: "Paper", href: "https://arxiv.org/abs/2504.21022" }],
    placeholder: false,
  },
  {
    title: "Statistical Reachability Analysis of Stochastic Cyber-Physical Systems under Distribution Shift",
    authors: "Navid Hashemi, Lars Lindemann, Jyotirmoy V. Deshmukh",
    venue: "IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems",
    year: "2024",
    note: "Volume 43, Issue 11, pages 4250–4261",
    links: [{ label: "Paper", href: "https://doi.org/10.1109/TCAD.2024.3438072" }],
    placeholder: false,
  },
  {
    title: "Systematic Translation from Natural Language Robot Task Descriptions to STL",
    authors: "Sara Mohammadinejad, Sheryl Paul, Yuan Xia, Vidisha Kudalkar, Jesse Thomason, Jyotirmoy V. Deshmukh",
    venue: "AISoLA — Bridging the Gap Between AI and Reality",
    year: "2024",
    note: "Pages 259–276",
    links: [{ label: "Paper", href: "https://doi.org/10.1007/978-3-031-75434-0_18" }],
    placeholder: false,
  },
  {
    title: "Formal Verification and Control with Conformal Prediction",
    authors: "Lars Lindemann, Yiqi Zhao, Xinyi Yu, George J. Pappas, Jyotirmoy V. Deshmukh",
    venue: "arXiv preprint",
    year: "2024",
    links: [{ label: "Paper", href: "https://arxiv.org/abs/2409.00536" }],
    placeholder: false,
  },
  {
    title: "Robust Conformal Prediction for STL Runtime Verification under Distribution Shift",
    authors: "Yiqi Zhao, Bardh Hoxha, Georgios Fainekos, Jyotirmoy V. Deshmukh, Lars Lindemann",
    venue: "ACM/IEEE International Conference on Cyber-Physical Systems",
    year: "2024",
    note: "Pages 169–179",
    links: [{ label: "Paper", href: "https://doi.org/10.1109/ICCPS61052.2024.00022" }],
    placeholder: false,
  },
  {
    title: "Data-Driven Reachability Analysis of Stochastic Dynamical Systems with Conformal Inference",
    authors: "Navid Hashemi, Xin Qin, Lars Lindemann, Jyotirmoy V. Deshmukh",
    venue: "IEEE Conference on Decision and Control",
    year: "2023",
    note: "Pages 3102–3109",
    links: [{ label: "Paper", href: "https://doi.org/10.1109/CDC49753.2023.10384213" }],
    placeholder: false,
  },
  {
    title: "LB4TL: A Smooth Semantics for Temporal Logic to Train Neural Feedback Controllers",
    authors: "Navid Hashemi, Samuel Williams, Bardh Hoxha, Danil V. Prokhorov, Georgios Fainekos, Jyotirmoy V. Deshmukh",
    venue: "IFAC Conference on Analysis and Design of Hybrid Systems",
    year: "2024",
    note: "IFAC-PapersOnLine 58(11), pages 183–188",
    links: [{ label: "Paper", href: "https://doi.org/10.1016/j.ifacol.2024.07.445" }],
    placeholder: false,
  },
  {
    title: "A Neurosymbolic Approach to the Verification of Temporal Logic Properties of Learning-enabled Control Systems",
    authors: "Navid Hashemi, Bardh Hoxha, Tomoya Yamaguchi, Danil Prokhorov, Georgios Fainekos, Jyotirmoy Deshmukh",
    venue: "arXiv:2303.05394",
    year: "2023",
    links: [{ label: "Paper", href: "https://arxiv.org/abs/2303.05394" }],
    placeholder: false,
  },
  {
    title: "Learning from Demonstrations Using Signal Temporal Logic in Stochastic and Continuous Domains",
    authors: "Aniruddh G. Puranic, Jyotirmoy V. Deshmukh, Stefanos Nikolaidis",
    venue: "IEEE Robotics and Automation Letters (RA-L); IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)",
    year: "2021",
    links: [{ label: "DOI", href: "https://doi.org/10.1109/LRA.2021.3096162" }],
    placeholder: false,
  },
  {
    title: "Specifying and Detecting Temporal Patterns With Shape Expressions",
    authors: "Dejan Nickovic, Xin Qin, Thomas Ferrère, Cristinel Mateis, Jyotirmoy V. Deshmukh",
    venue: "International Journal on Software Tools for Technology Transfer (STTT)",
    year: "2021",
    links: [{ label: "Paper", href: "https://link.springer.com/article/10.1007/s10009-021-00617-1" }],
    placeholder: false,
  },
  {
    title: "Mining Shape Expressions from Positive Examples",
    authors: "Ezio Bartocci, Jyotirmoy V. Deshmukh, Felix Gigler, Cristinel Mateis, Dejan Nickovic, Xin Qin",
    venue: "IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems (TCAD)",
    year: "2021",
    links: [{ label: "DOI", href: "https://doi.org/10.1109/TCAD.2020.3037018" }],
    placeholder: false,
  },
  {
    title: "Statistical Verification of Autonomous Systems using Surrogate Models and Conformal Inference",
    authors: "Chuchu Fan, Xin Qin, Yuan Xia, Aditya Zutshi, Jyotirmoy Deshmukh",
    venue: "CoRR abs/2004.00279",
    year: "2021",
    links: [{ label: "Paper", href: "https://arxiv.org/abs/2004.00279" }],
    placeholder: false,
  },
  {
    title: "PerceMon: Online Monitoring for Perception Systems",
    authors: "Anand Balakrishnan, Jyotirmoy V. Deshmukh, Bardh Hoxha, Tomoya Yamaguchi, Georgios Fainekos",
    venue: "CoRR abs/2108.08289",
    year: "2021",
    links: [{ label: "Paper", href: "https://arxiv.org/abs/2108.08289" }],
    placeholder: false,
  },
  {
    title: "Clairvoyant Monitoring for Signal Temporal Logic",
    authors: "Xin Qin, Jyotirmoy V. Deshmukh",
    venue: "International Conference on Formal Modeling and Analysis of Timed Systems (FORMATS)",
    year: "2020",
    links: [{ label: "DOI", href: "https://doi.org/10.1007/978-3-030-57628-8_13" }],
    placeholder: false,
  },
  {
    title: "Structured Reward Shaping using Signal Temporal Logic Specifications",
    authors: "Anand Balakrishnan, Jyotirmoy V. Deshmukh",
    venue: "IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)",
    year: "2019",
    links: [
      { label: "Paper", href: "https://anandb.me/research/iros2019.pdf" },
      { label: "Code", href: "https://github.com/anand-bala/Project1" },
    ],
    placeholder: false,
  },
 ];
